# Generated by Django 6.0.7 on 2026-07-31 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_departement', models.CharField(max_length=30, unique=True)),
                ('abreviation', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('abreviation', models.CharField(max_length=20, unique=True)),
                ('maquette', models.IntegerField(default=0)),
                ('A', models.IntegerField(default=0)),
                ('O', models.IntegerField(default=0)),
                ('P', models.IntegerField(default=0)),
                ('C', models.IntegerField(default=0)),
                ('T', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Collaborateur',
            fields=[
                ('it', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('matricule', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('cin', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('nom_complete', models.CharField(max_length=80)),
                ('lot', models.CharField(blank=True, choices=[('A', 'Anapec'), ('O', 'CDI'), ('P', 'Pro'), ('E', 'Tam'), ('C', 'Cadre')], max_length=5)),
                ('eq', models.CharField(default='Inconnu', max_length=10)),
                ('shift', models.CharField(blank=True, choices=[('A', '6-15'), ('B', '15-23'), ('N', '23-6'), ('H 4-8', '4 équipes'), ('AD', 'Administratif')], max_length=15, null=True)),
                ('sexe', models.IntegerField(choices=[(0, 'Femme'), (1, 'Homme')])),
                ('post', models.CharField(blank=True, choices=[('O', 'Opérateur'), ('T', 'Team Leader')], max_length=1, null=True)),
                ('ru_it', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordonnes', to='Collaborateur.collaborateur')),
                ('departement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Collaborateur.departement', to_field='abreviation')),
                ('unite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rus', to='Collaborateur.unite', to_field='abreviation')),
            ],
        ),
    ]
