# Generated by Django 6.0.7 on 2026-08-22 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Collaborateur', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborateur',
            name='post',
        ),
        migrations.RemoveField(
            model_name='unite',
            name='O',
        ),
    ]
