# Generated by Django 6.0.7 on 2026-08-27 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collaborateur', '0003_departement_rh_responsable'),
        ('utilisateur', '0004_rh_alter_utilisateur_it'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='rh_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements', to='utilisateur.utilisateur', verbose_name='RH Responsable'),
        ),
    ]
