# Generated by Django 6.0.7 on 2026-08-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collaborateur', '0004_alter_departement_rh_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='maquette',
            field=models.IntegerField(default=0),
        ),
    ]
