# Generated by Django 6.0.7 on 2026-08-28 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collaborateur', '0005_departement_maquette'),
        ('utilisateur', '0009_utilisateur_doit_changer_mdp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departement',
            name='rh_responsable',
        ),
        migrations.AddField(
            model_name='departement',
            name='ADNMIN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departement_admine', to='utilisateur.utilisateur', verbose_name='admine'),
        ),
        migrations.AddField(
            model_name='departement',
            name='DRH',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements_DRH', to='utilisateur.utilisateur', verbose_name=' DRH'),
        ),
        migrations.AddField(
            model_name='departement',
            name='HRBP',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements_RH', to='utilisateur.utilisateur', verbose_name='RH Responsable'),
        ),
    ]
