# Generated by Django 6.0.7 on 2026-08-28 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collaborateur', '0006_remove_departement_rh_responsable_departement_adnmin_and_more'),
        ('utilisateur', '0009_utilisateur_doit_changer_mdp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='ADNMIN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departement_admine', to='utilisateur.utilisateur', verbose_name='admin'),
        ),
    ]
