# Generated by Django 6.0.7 on 2026-08-29 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collaborateur', '0007_alter_departement_adnmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='ADNMIN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departement_admine', to='Collaborateur.collaborateur', verbose_name='admin'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='DRH',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements_DRH', to='Collaborateur.collaborateur', verbose_name=' DRH'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='HRBP',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements_RH', to='Collaborateur.collaborateur', verbose_name='RH Responsable'),
        ),
    ]
