# Generated by Django 6.0.7 on 2026-08-30 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Collaborateur', '0008_alter_departement_adnmin_alter_departement_drh_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departement',
            old_name='ADNMIN',
            new_name='ADMIN',
        ),
    ]
