# Generated by Django 6.0.7 on 2026-09-03 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collaborateur', '0009_rename_adnmin_departement_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='PILOT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements_PILOT', to='Collaborateur.collaborateur', verbose_name=' DRH'),
        ),
    ]
