# Generated by Django 6.0.7 on 2026-09-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collaborateur', '0011_alter_departement_pilot'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborateur',
            name='Equipe',
            field=models.CharField(default='Inconnu', max_length=10),
        ),
    ]
