# Generated by Django 6.0.7 on 2026-09-04 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Collaborateur', '0012_collaborateur_equipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborateur',
            name='Equipe',
        ),
    ]
