# Generated by Django 6.0.7 on 2026-09-08 14:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collaborateur', '0014_remove_collaborateur_cin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('abreviation', models.CharField(max_length=20, unique=True)),
                ('maquette', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('A', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('P', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('C', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('T', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Équipe',
                'verbose_name_plural': 'Équipes',
            },
        ),
        migrations.RemoveField(
            model_name='collaborateur',
            name='unite',
        ),
        migrations.AlterModelOptions(
            name='collaborateur',
            options={'verbose_name': 'Collaborateur', 'verbose_name_plural': 'Collaborateurs'},
        ),
        migrations.AlterModelOptions(
            name='departement',
            options={'verbose_name': 'Département', 'verbose_name_plural': 'Départements'},
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborateurs', to='Collaborateur.departement', to_field='abreviation'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='ADMIN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departement_admine', to='Collaborateur.collaborateur', verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='DRH',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements_DRH', to='Collaborateur.collaborateur', verbose_name='DRH'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='PILOT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements_PILOT', to='Collaborateur.collaborateur', verbose_name='PILOT'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='maquette',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='eq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rus', to='Collaborateur.equipe', to_field='abreviation'),
        ),
        migrations.DeleteModel(
            name='Unite',
        ),
    ]
