# Generated by Django 6.0.7 on 2026-09-09 08:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collaborateur', '0015_equipe_remove_collaborateur_unite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborateur',
            name='eq',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.CreateModel(
            name='HistoriqueMaquetteN1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n1_it', models.CharField(max_length=8)),
                ('n1_nom', models.CharField(blank=True, max_length=80)),
                ('ancien_A', models.IntegerField(blank=True, null=True)),
                ('ancien_T', models.IntegerField(blank=True, null=True)),
                ('ancien_P', models.IntegerField(blank=True, null=True)),
                ('ancien_C', models.IntegerField(blank=True, null=True)),
                ('nouveau_A', models.IntegerField(default=0)),
                ('nouveau_T', models.IntegerField(default=0)),
                ('nouveau_P', models.IntegerField(default=0)),
                ('nouveau_C', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Collaborateur.departement', to_field='abreviation')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Collaborateur.collaborateur')),
                ('n1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_maquette', to='Collaborateur.collaborateur')),
            ],
            options={
                'verbose_name': 'Historique maquette N+1',
                'verbose_name_plural': 'Historiques maquette N+1',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MaquetteN1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('T', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('P', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('C', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquettes_n1', to='Collaborateur.departement', to_field='abreviation')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquettes_n1_attribuees', to='Collaborateur.collaborateur')),
                ('n1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maquette_n1', to='Collaborateur.collaborateur')),
            ],
            options={
                'verbose_name': 'Maquette N+1',
                'verbose_name_plural': 'Maquettes N+1',
            },
        ),
    ]
