# Generated by Django 6.0.7 on 2026-09-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collaborateur', '0016_alter_collaborateur_eq_historiquemaquetten1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiquemaquetten1',
            name='nature',
            field=models.CharField(choices=[('MODIFICATION', 'Modification manuelle par le PILOT'), ('AUTO_CREATION', 'Nouveau N+1 détecté (créé à 0)'), ('INACTIVATION', "N'est plus N+1 (rôle perdu)"), ('REACTIVATION', 'Redevenu N+1')], default='MODIFICATION', max_length=15),
        ),
        migrations.AddField(
            model_name='maquetten1',
            name='actif',
            field=models.BooleanField(default=True),
        ),
    ]
