# Generated by Django 6.0.7 on 2026-09-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Collaborateur', '0017_historiquemaquetten1_nature_maquetten1_actif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departement',
            name='maquette',
        ),
    ]
