# Generated by Django 6.0.7 on 2026-10-18 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Collaborateur', '0018_remove_departement_maquette'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipe',
        ),
    ]
