# Generated by Django 6.0.7 on 2026-07-31 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Collaborateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='utilisateur',
            fields=[
                ('password', models.CharField(blank=True, max_length=277)),
                ('role', models.CharField(choices=[('N+1', 'N+1'), ('N+2', ' N+2'), ('N+3', 'N+3'), ('N+4', 'N+4')], max_length=5)),
                ('it', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='utilisateur', serialize=False, to='Collaborateur.collaborateur')),
                ('N1', models.IntegerField(choices=[('1', True), ('0', False)])),
                ('N2', models.IntegerField(choices=[('1', True), ('0', False)])),
                ('N3', models.IntegerField(choices=[('1', True), ('0', False)])),
                ('N4', models.IntegerField(choices=[('1', True), ('0', False)])),
            ],
        ),
    ]
