# Generated by Django 6.0.7 on 2026-08-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_utilisateur_rh_alter_utilisateur_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='RH',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('N+1', 'N+1'), ('N+2', ' N+2'), ('N+3', 'N+3'), ('N+4', 'N+4')], max_length=5),
        ),
    ]
