# Generated by Django 6.0.7 on 2026-08-27 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collaborateur', '0002_remove_collaborateur_post_remove_unite_o'),
        ('utilisateur', '0003_remove_utilisateur_rh_alter_utilisateur_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='RH',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='utilisateur', serialize=False, to='Collaborateur.collaborateur')),
                ('role', models.CharField(choices=[('HRBP', 'Human Resources Business Partner'), ('ADMIN', 'admin')])),
            ],
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='it',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='compte_utilisateur', serialize=False, to='Collaborateur.collaborateur'),
        ),
    ]
