# Generated by Django 6.0.7 on 2026-08-27 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collaborateur', '0004_alter_departement_rh_responsable'),
        ('utilisateur', '0004_rh_alter_utilisateur_it'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='it',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='utilisateur', serialize=False, to='Collaborateur.collaborateur'),
        ),
        migrations.DeleteModel(
            name='RH',
        ),
    ]
