# Generated by Django 6.0.7 on 2026-08-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0005_alter_utilisateur_it_delete_rh'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='ADMIN',
            field=models.IntegerField(choices=[('1', True), ('0', False)], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='HRBP',
            field=models.IntegerField(choices=[('1', True), ('0', False)], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('N+1', 'N+1'), ('N+2', ' N+2'), ('N+3', 'N+3'), ('N+4', 'N+4'), ('HRBP', 'Human Resources Business Partner'), ('ADMIN', 'admin')], max_length=5),
        ),
    ]
