# Generated by Django 6.0.7 on 2026-08-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0006_utilisateur_admin_utilisateur_hrbp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('N+1', 'N+1'), ('N+2', ' N+2'), ('N+3', 'N+3'), ('N+4', 'N+4'), ('HRBP', 'Human Resources Business Partner'), ('ADMIN', 'admin')], max_length=10),
        ),
    ]
