# Generated by Django 6.0.7 on 2026-08-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0008_utilisateur_super_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='doit_changer_mdp',
            field=models.BooleanField(default=False),
        ),
    ]
