# Generated by Django 6.0.7 on 2026-09-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0010_utilisateur_drh_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='PILOT',
            field=models.IntegerField(choices=[('1', True), ('0', False)], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('N+1', 'N+1'), ('N+2', ' N+2'), ('N+3', 'N+3'), ('N+4', 'N+4'), ('HRBP', 'Human Resources Business Partner'), ('ADMIN', 'admin'), ('SUPER', 'super admin'), ('DRH', 'Directeur des Ressources Humaines'), ('PILOT', 'PILOT')], max_length=10),
        ),
    ]
