# Generated by Django 6.0.7 on 2026-10-16 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0012_loginlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='doit_changer_mdp',
        ),
    ]
