# Generated by Django 6.0.7 on 2026-09-04 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='histo_import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('depar', models.IntegerField()),
                ('modif', models.IntegerField()),
                ('utilisateur', models.CharField(blank=True, max_length=50, null=True)),
                ('nom_fichier', models.CharField(blank=True, max_length=255, null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='imports/')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('SUCCES', 'Succès'), ('ECHEC', 'Échec'), ('PARTIEL', 'Succès partiel')], default='SUCCES', max_length=20)),
                ('nb_lignes_total', models.PositiveIntegerField(default=0)),
                ('nb_crees', models.PositiveIntegerField(default=0)),
                ('nb_supprimes', models.PositiveIntegerField(default=0)),
                ('nb_ignores', models.PositiveIntegerField(default=0)),
                ('nb_erreurs', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='histo_import_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('IGNORE', 'Ignoré'), ('ERREUR', 'Erreur')], max_length=20)),
                ('it', models.CharField(blank=True, max_length=50, null=True)),
                ('champ_modifie', models.CharField(blank=True, max_length=100, null=True)),
                ('ancienne_valeur', models.CharField(blank=True, max_length=255, null=True)),
                ('nouvelle_valeur', models.CharField(blank=True, max_length=255, null=True)),
                ('message_erreur', models.TextField(blank=True, null=True)),
                ('import_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='import_data.histo_import')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
