# Generated by Django 6.0.7 on 2026-09-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histo_import',
            name='depar',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='histo_import',
            name='modif',
            field=models.IntegerField(default=0),
        ),
    ]
