# Generated by Django 6.0.7 on 2026-09-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0002_alter_histo_import_depar_alter_histo_import_modif'),
    ]

    operations = [
        migrations.AddField(
            model_name='histo_import',
            name='erreur',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='histo_import',
            name='supprime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='histo_import_detail',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='histo_import_detail',
            name='nom_complete',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
