# Generated by Django 6.0.7 on 2026-09-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0003_histo_import_erreur_histo_import_supprime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='histo_import',
            name='duree',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
