# Generated by Django 6.0.7 on 2026-09-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_data', '0004_histo_import_duree'),
    ]

    operations = [
        migrations.AddField(
            model_name='histo_import',
            name='synthese_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
