# Generated by Django 6.0.7 on 2026-07-31 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Collaborateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaborateur', models.CharField(max_length=30)),
                ('initial', models.CharField(max_length=30)),
                ('acceuil', models.CharField(max_length=30)),
                ('etat', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('lu', models.CharField(choices=[('0', 'true'), ('1', 'false')], default=0)),
                ('emetteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declaration_effectif_Alert_recepteur', to='Collaborateur.collaborateur')),
                ('recepteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Collaborateur.collaborateur')),
            ],
        ),
        migrations.CreateModel(
            name='declaration_effectif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('nature', models.CharField(choices=[('V', 'valider'), ('D', 'depart'), ('C', 'Changer'), ('A', 'ajouter')], max_length=1)),
                ('Ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations_faite_par', to='Collaborateur.collaborateur')),
                ('collaborateur_it', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations_concernees', to='Collaborateur.collaborateur')),
                ('nv_Ru', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations_vers', to='Collaborateur.collaborateur')),
            ],
        ),
    ]
