# Generated by Django 6.0.7 on 2026-08-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaration_effectif', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='lu',
            field=models.BooleanField(default=False),
        ),
    ]
