# Generated by Django 6.0.7 on 2026-08-30 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collaborateur', '0008_alter_departement_adnmin_alter_departement_drh_and_more'),
        ('declaration_effectif', '0002_alter_alert_lu'),
    ]

    operations = [
        migrations.AddField(
            model_name='historique',
            name='dpt_acceuil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DPT_acceuil', to='Collaborateur.departement', to_field='abreviation'),
        ),
        migrations.AddField(
            model_name='historique',
            name='dpt_init',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DPT_initial', to='Collaborateur.departement', to_field='abreviation'),
        ),
    ]
